version: '3.8'

services:
  arxivllama:
    build: .
    container_name: arxivllama
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0